[workspace]
channels = ["conda-forge"]
name = "matchmaking"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[tasks]
check-lint-format = "ruff check . && ruff format --check ."
fix-lint-format = "ruff check --fix . && ruff format ."
tests = "pytest --cov=matchmaking --cov-report=html --cov-report=markdown --cov-report=xml tests/ --cache-clear"
pc-run-all = "pre-commit run --all-files --show-diff-on-failure"
benchmark = "./benchmark/run_benchmark.sh --headless"
benchmark-ui = "./benchmark/run_benchmark.sh --ui"
benchmark-dist = "./benchmark/run_benchmark.sh --distributed --headless"
benchmark-dist-ui = "./benchmark/run_benchmark.sh --distributed --ui"

[dependencies]
python = ">=3.11,<3.12"
pip = ">=25"
pixi-pycharm = ">=0,<1"
pydantic = ">=2.12,<3"
pyyaml = ">=6.0,<7"
pytest = ">=8.1"
ruff = ">=0.15,<0.16"
pytest-cov = ">=7.1,<8"
packaging = ">=26.0,<27"
pre-commit = ">=4.1,<5"
locust = ">=2.43,<3"
redis-py = ">=7.4,<8"

[pypi-dependencies]
matchmaking = { path = ".", editable = true }

[feature.analysis.dependencies]
matplotlib = ">=3.9"
pandas = ">=2.2"
jupyterlab = ">=4.2"

[feature.analysis.tasks]
lab = "jupyter lab analysis/"

[environments]
analysis = { features = ["analysis"], solve-group = "analysis" }
