job_type_priorities:
  - WGProduction
  - Sprucing
  - MCFastSimulation
  - MCSimulation
  - User
  - Merge
  - MCRConstruction
  - APMerge
  - APPostProc
  - MCMerge
  - LbAPI

running_limits:
  # Global limit by default
  default:
    MCSimulation: 1000
    User: 200

  # Local limits by site
  LCG.CERN.ch:
    WGProduction: 1000
    MCSimulation: 5000

  LCG.IN2P3.fr:
    MCSimulation: 800
    User: 50
