name: Python CI

on:
  push:
    branches-ignore:
      - release-please-**
  pull_request:
    branches: [ main ]
    branches-ignore:
      - release-please-**

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          frozen: true
          cache: true

      - name: Run pre-commit
        run: pixi run pc-run-all

      - name: Run Tests (Pytest)
        run: pixi run tests

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./htmlcov/,coverage.md,coverage.xml
          fail_ci_if_error: false

  release-please:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.repository == 'devlink42/poc-dirac-job-matchmaking' && github.ref_name == 'main' }}
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target-branch: ${{ github.ref_name }}
          config-file: release-please-config.json
