name: Python CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          frozen: true
          cache: true

      - name: Run pre-commit
        run: pixi run pc-run-all --show-diff-on-failure

      - name: Run Tests (Pytest)
        run: pixi run tests

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v6
        with:
          files: ./coverage.xml
          fail_ci_if_error: false
